server:
  port: 8083

resilience4j:
  circuitbreaker:
    instances:
      paymentCB:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
