server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: http://localhost:8081/
          predicates:
            - Path=/customer/**
          filters:
            - RewritePath=/customer/(?<segment>.*), /${segment}
        - id: billing-service
          uri: http://localhost:8082/
          predicates:
            - Path=/billing/**
          filters:
            - RewritePath=/billing/(?<segment>.*), /${segment}
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 5
            redis-rate-limiter.burstCapacity: 10
